app/ui/redux/modules/global.js

Add default filename with date for export

---

app/main/window-utils.js

Otherwise it won't work on Windows 😞

Use CmdOrCtrl on Quit

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

- Adds a PR template encouraging descriptive PR descriptions that contributors can use for future changes.
- Formats Issue Template in a similar fashion to the new PR template.
- A high-level English description allows for reviewers to verify the intended changes are the changes reflected in the code.
- A consistent PR style makes it easier for contributors to understand what changes are being made.
- Having descriptive PRs will allow for easy understanding and reasoning of changes in the future when browsing past contributions.
N/A
N/A
**Related Issue**: N/A

Update Issue and PR templates

---

app/ui/components/dropdowns/preview-mode-dropdown.js
app/ui/components/response-pane.js

* Add a new button on the response preview pane
* Save full response to file when button clicked
closes https://github.com/getinsomnia/insomnia/issues/192

Save full response to a file

---

app/templating/extensions/__tests__/response-extension.test.js
app/templating/extensions/response-extension.js
app/ui/components/base/editable.js
app/ui/components/codemirror/extensions/nunjucks-tags.js
app/ui/components/dropdowns/environments-dropdown.js
app/ui/components/dropdowns/workspace-dropdown.js
app/ui/components/editors/auth/o-auth-2.js
app/ui/components/editors/cookies-editor.js
app/ui/components/key-value-editor/row.js
app/ui/components/modals/request-create-modal.js
app/ui/components/modals/request-render-error-modal.js
app/ui/components/modals/request-settings-modal.js
app/ui/components/modals/request-switcher-modal.js
app/ui/components/modals/workspace-environments-edit-modal.js
app/ui/components/modals/workspace-settings-modal.js
app/ui/components/modals/workspace-share-settings-modal.js
app/ui/components/response-pane.js
app/ui/components/templating/tag-editor.js
app/ui/components/templating/variable-editor.js
app/ui/components/viewers/response-cookies-viewer.js
app/ui/css/components/modal.less

This is another step towards implementing request chaining. 
Optional:
Here's a screenshot of using the tag to select the title of the first RSS feed item on https://insomnia.rest/index.xml
**Related Issue**: Related to #210

Finalize {% response ... %} Tag

---

app/common/constants.js

Fix NTLM typo
Typo 
_(Any important detail regarding how functionality of Insomnia changes due to the code changes in included in this PR.)_
_(Anything else you might want to mention regarding this PR, if any.)_
**Related Issue**: Fixes #242

fix NTLM typo

---

CONTRIBUTING.md
app/main.development.js
app/main/updates.js
app/main/window-utils.js
app/package.json
app/templating/extensions/now-extension.js
app/ui/components/codemirror/extensions/nunjucks-tags.js
app/ui/components/modals/workspace-settings-modal.js
app/ui/containers/app.js
app/ui/css/constants/dimensions.less

- Fixes some issues where 1px borders were disappearing

Tweaks and fixes for next release

---

app/ui/components/editors/auth/o-auth-2.js

OAuth password field should abide by password setting

---

app/ui/components/templating/tag-editor.js

Show request folder as prefix in the request selector

Show folder name in response tag dialog

---

app/__mocks__/node-libcurl.js
app/models/settings.js
app/network/network.js
app/ui/components/settings/general.js

Closes #189 
Sorry for the delay.
I will have a look if its possible to use the noproxy option provided by libcurl. That should be much cleaner.
Update: I figured out how to use the noproxy option and changed the implementation to use it :)

Add no proxy support

---

app/main/window-utils.js
app/ui/containers/app.js

Add send shortcut for cmd+R and F5

---

app/common/constants.js

* Made lists of reason phrases and descriptions consistent
* Added reason phrases and descriptions for additional codes covered by RFCs
See discussion in issue #303.
_none_
_none_
**Related Issue**: #303.

Added missing reason phrases and descriptions, made lists consistent

---

app/package.json
app/ui/components/sidebar/sidebar-children.js
app/ui/components/sidebar/sidebar-request-group-row.js
app/ui/components/sidebar/sidebar-request-row.js
app/ui/components/sidebar/sidebar.js
app/ui/components/wrapper.js
app/ui/containers/app.js
app/ui/redux/selectors.js

Closes #301 
- Can now drag folders to parents that don't already contain folders
- Folders and requests can now be ordered relative to each other
- A few other fixes...

Much better sidebar sorting

---

app/ui/components/viewers/response-viewer.js
package.json

As discussed earlier here: #323

Ability to preview PDF on Visual preview mode

---

app/common/import.js
app/ui/components/editors/auth/auth-wrapper.js
app/ui/components/modals/ask-modal.js
app/ui/components/wrapper.js
app/ui/redux/modules/global.js

Closes #337 
This PR adds the ability to export private environments. This will only prompt the user if they actually have private environments.

Add prompt to export private environments

---

app/common/import.js
app/models/workspace-meta.js
app/renderer.html
app/sync/index.js
app/ui/components/dropdowns/sync-dropdown.js
app/ui/components/dropdowns/workspace-dropdown.js
app/ui/components/sidebar/sidebar.js
app/ui/components/tooltip.js
app/ui/components/wrapper.js
app/ui/containers/app.js
app/ui/redux/selectors.js

Put an asterisk inside workspace dropdown if a new workspace was created without the user knowing (import or sync). The asterisk is removed when the workspace dropdown is hidden the next time.

Mark new workspaces in UI

---

app/common/fetch.js
app/sync/index.js
app/ui/components/settings/plugins.js
app/ui/components/toast.js

This PR changes the notification fetching behavior. There are now three endpoints that get pinged.
- `https://api.insomnia.rest/notification` – for logged-in users
- eg. subscription events, payment failures, etc
- `https://insomnia.rest/notifications/${version}.json` – for version-specific notifications
- upgrade notifications, new features
- `https://insomnia.rest/notificatons/all.json` – for generic announcement notifications
- generic announcements like blog posts
_Note: This PR also adds a loading indicator for refreshing plugins_

Extra Notifications Endpoints

---

app/common/misc.js
app/ui/components/editors/body/graph-ql-editor.js

GraphQL variables now object instead of string

---

app/common/prettify.js

Fixes #271 
This PR makes the JSON prettifier ignore Nunjucks tags.
```
{"foo": {{ bar }}}
```
Becomes
```
{
"foo": {{ bar }}
}
```
Instead of 
```
{
"foo": {
{ 
bar 
}
}
}
```
This is a super hacky solution, but it works 👍

Don't prettify nunjucks tags

---

app/ui/components/editors/auth/o-auth-2-auth.js
app/ui/components/editors/body/graph-ql-editor.js
app/ui/components/time-from-now.js
app/ui/css/components/graph-ql-editor.less

This PR improves the GraphQL editing experience based on some early community feedback.

GraphQL updates and fixes

---

app/ui/components/viewers/response-viewer.js

Add response preview for audio payloads

---

app/ui/components/editors/body/graph-ql-editor.js

Add a button to refresh the GraphQL schema

---

app/common/__fixtures__/prettify/nunjucks-input.json
app/common/__fixtures__/prettify/nunjucks-output.json
app/common/prettify.js

Closes #477 
This PR refactors `prettify.js` to built Nunjucks handling into the lexer instead of relying on slow/memory-hogging regular expressions.

Built Nunjucks handling into prettify algorithm

---

app/network/network.js

Fix legacy certificate check

---

.eslintrc
app/plugins/index.js
app/templating/extensions/__tests__/response-extension.test.js
app/templating/extensions/index.js
app/templating/extensions/request-extension.js
app/templating/extensions/response-extension.js
app/templating/index.js
app/templating/utils.js
app/ui/components/templating/tag-editor.js
package-lock.json
package.json

Flow and robustness to template tag editor

---

app/templating/extensions/response-extension.js
app/templating/utils.js
app/ui/components/cookie-list.js
app/ui/components/modals/nunjucks-modal.js
app/ui/components/rendered-text.js
app/ui/components/templating/tag-editor.js

Closes #510 
This change makes it possible to use dynamic values in template tags without editing the raw Nunjucks.

Support for tag editor dynamic variable args

---

app/__tests__/package.test.js
app/analytics/index.js
app/network/__tests__/multipart.test.js
app/network/__tests__/network.test.js
app/network/multipart.js
app/network/network.js
app/package.json
app/templating/__tests__/utils.test.js
app/templating/extensions/index.js
app/templating/utils.js
app/ui/components/dropdowns/content-type-dropdown.js
app/ui/components/pdf-viewer.js
app/ui/components/request-pane.js
app/ui/components/response-pane.js
app/ui/components/templating/tag-editor.js
app/ui/components/viewers/response-viewer.js
flow-typed/form-data.js
flow-typed/pdfjs-dist.js
package-lock.json
package.json

This PR adds the ability to have a `boolean` type for a plugin argument.
You can specify it like this in your plugin: 
```js
args: [
{
displayName: 'Add Fries',
type: 'boolean'
},
// ...
]
```
And here's what it looks like in the UI:

Add boolean type to template tags

---

app/templating/__tests__/utils.test.js
app/templating/extensions/__tests__/file-extension.test.js
app/templating/extensions/__tests__/test.txt
app/templating/extensions/file-extension.js
app/templating/extensions/index.js
app/templating/utils.js
app/ui/components/base/file-input-button.js
app/ui/components/templating/tag-editor.js

This PR adds a new template tag to allow the user to read files from the file system.

New Template Tag to read file from filesystem

---

app/templating/extensions/__tests__/file-extension.test.js
app/templating/extensions/__tests__/hash-extension.test.js
app/templating/extensions/hash-extension.js
app/templating/extensions/index.js
app/templating/extensions/uuid-extension.js
app/ui/components/templating/tag-editor.js
flow-typed/uuid.js

Closes #537 
This PR adds a new template tag for applying a hash to a value.

Add Template Tag for hashing values

---

app/ui/components/modals/index.js
app/ui/containers/app.js
app/ui/redux/modules/global.js

Fixes #551
This PR adds a drop handler and prompts the user to import it if it can.

Drag and drop import files

---

app/main/window-utils.js
app/renderer.html
app/ui/index.js
package-lock.json
package.json
webpack/webpack.config.development.babel.js
webpack/webpack.config.electron.babel.js

This PR simplifies the code required to launch the app and handle hot reloading. It also adds a `Content-Security-Policy` to help prevent XSS attacks.

Simplified app launch logic

---

README.md

Not sure if you do maintain the plugin list but here you go :slightly_smiling_face:

Add mention of UK sort code plugin

---

packages/insomnia-app/app/models/request.js
packages/insomnia-app/app/network/__tests__/network.test.js
packages/insomnia-app/app/network/network.js
packages/insomnia-app/app/ui/components/base/button.js
packages/insomnia-app/app/ui/components/editors/auth/asap-auth.js
packages/insomnia-app/app/ui/components/editors/auth/auth-wrapper.js
packages/insomnia-app/app/ui/components/editors/auth/aws-auth.js
packages/insomnia-app/app/ui/components/editors/auth/basic-auth.js
packages/insomnia-app/app/ui/components/editors/auth/bearer-auth.js
packages/insomnia-app/app/ui/components/editors/auth/digest-auth.js
packages/insomnia-app/app/ui/components/editors/auth/hawk-auth.js
packages/insomnia-app/app/ui/components/editors/auth/ntlm-auth.js
packages/insomnia-app/app/ui/components/key-value-editor/row.js
packages/insomnia-app/app/ui/css/components/forms.less
packages/insomnia-app/app/ui/css/components/key-value-editor.less
packages/insomnia-app/package.json

AWS Multi-Factor Authentication

---

packages/insomnia-app/app/models/__tests__/request.test.js
packages/insomnia-app/app/models/request-meta.js
packages/insomnia-app/app/models/request.js
packages/insomnia-app/app/ui/components/dropdowns/content-type-dropdown.js
packages/insomnia-app/app/ui/components/wrapper.js
packages/insomnia-app/app/ui/containers/app.js

[Feature] Save request body when switching to 'No Body' (#752)

---

packages/insomnia-app/app/ui/components/dropdowns/request-group-actions-dropdown.js
packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js
packages/insomnia-app/app/ui/components/modals/request-settings-modal.js
packages/insomnia-app/app/ui/components/sidebar/sidebar-children.js
packages/insomnia-app/app/ui/components/sidebar/sidebar-request-group-row.js
packages/insomnia-app/app/ui/components/sidebar/sidebar.js
packages/insomnia-app/app/ui/components/wrapper.js
packages/insomnia-app/app/ui/containers/app.js

Closes #403
Also an option to move or copy individual requests from the request settings dialog:

Move folders and requests to new workspaces

---

README.md

Add insomnia-plugin-js-eval to Plugins list

---

README.md

Add Faker Plugin list to Community Plugins in README

---

packages/insomnia-app/app/models/environment.js
packages/insomnia-app/app/ui/components/dropdowns/environments-dropdown.js
packages/insomnia-app/app/ui/components/modals/workspace-environments-edit-modal.js
packages/insomnia-app/app/ui/containers/app.js
packages/insomnia-app/app/ui/css/components/environment-modal.less
packages/insomnia-app/flow-typed/react-sortable-hoc.js
packages/insomnia-app/package-lock.json
packages/insomnia-app/package.json

Closes #162 
This PR adds the ability to sort environments from within the environment editor.

Sortable Environments

---

packages/insomnia-app/app/common/__tests__/misc.test.js
packages/insomnia-app/app/common/misc.js
packages/insomnia-app/app/ui/components/base/dropdown/dropdown.js
packages/insomnia-app/app/ui/components/base/highlight.js
packages/insomnia-app/app/ui/components/modals/cookies-modal.js
packages/insomnia-app/app/ui/components/modals/request-switcher-modal.js
packages/insomnia-app/app/ui/redux/selectors.js
packages/insomnia-app/flow-typed/deep-equal.js
packages/insomnia-app/flow-typed/fuzzysort.js
packages/insomnia-app/package.json

Before, fuzzy search was too loose. Now it's stricter and more intuitive!
- Now sort request switcher results by best match
- URL no longer filterable in sidebar
- Now throw out really bad matches

Better fuzzy search throughout app

---

plugins/insomnia-plugin-prompt/index.js

Add support for "Secure Text" option for prompts.
Closes #962

Add Secure Text option for prompts

---

packages/insomnia-app/app/ui/components/settings/theme.js
packages/insomnia-app/app/ui/css/constants/colors.less

Here's my first pass on this. I'm sure they're not perfect, but they look pretty ok to me.

One Light/Dark Themes

---

packages/insomnia-app/app/models/settings.js
packages/insomnia-app/app/ui/components/dropdowns/environments-dropdown.js
packages/insomnia-app/app/ui/components/settings/general.js
packages/insomnia-app/app/ui/components/sidebar/sidebar.js
packages/insomnia-app/app/ui/components/wrapper.js

Had to add this one to the grid, because border appeared outside of the
viewport.

Add bottom bar env highlight color style

---

packages/insomnia-app/app/sync/__tests__/sync.test.js
packages/insomnia-app/app/sync/index.js
packages/insomnia-app/app/ui/components/dropdowns/sync-dropdown.js
packages/insomnia-app/app/ui/components/modals/setup-sync-modal.js

Sync settings for blacklisting cookie jars and client certificates

---

packages/insomnia-app/app/network/o-auth-2/__tests__/grant-client-credentials.test.js
packages/insomnia-app/app/network/o-auth-2/constants.js
packages/insomnia-app/app/network/o-auth-2/get-token.js
packages/insomnia-app/app/network/o-auth-2/grant-client-credentials.js
packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js

Closes #716
This is an additional requirement in the oauth client credential grant used by Azure AD (#716).

Add resource param to client credential oauth grant.

---

packages/insomnia-importers/src/importers/har.js

This will fix an HAR export/import issue where names are lost.
Closes #1153

Preserve HAR entry comment during import

---

packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js
packages/insomnia-app/app/ui/css/components/dropdown.less
packages/insomnia-app/app/ui/css/components/forms.less
packages/insomnia-app/app/ui/css/components/graph-ql-editor.less
packages/insomnia-app/app/ui/css/layout/base.less

Better control over schema fetching

---

packages/insomnia-app/app/network/authentication.js
packages/insomnia-app/app/ui/components/editors/auth/hawk-auth.js

Adds support for Hawk's `ext` feature. Relates to #1263.

Add Hawk Ext feature

---

plugins/insomnia-plugin-request/index.js

Fix typo Paramter -> Parameter in plugin-request

---

packages/insomnia-importers/src/importers/openapi3.js

This is a port of fixes for Swagger from c2b4b37.
It allows to import OpenAPI specifications even if validation failed.

Try importing OpenAPI3 even if validation fails (Fixes #1354)

---

packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js

Fixes : https://github.com/getinsomnia/insomnia/issues/1398
My first PR here.  
Suggestions are appreciated.
Still trying to figure out how to record a screen-cast on linux.

Move request group to target workspace instead of duplicating

---

packages/insomnia-app/.electronbuilder

Closes #1704.
Issue:  
Resolved:

Set macOS icon to png for correct icon.icns build

---

package-lock.json
packages/insomnia-app/app/ui/components/modals/settings-modal.js
packages/insomnia-app/app/ui/components/settings/import-export.js
packages/insomnia-app/app/ui/components/wrapper.js
packages/insomnia-app/app/ui/containers/app.js
packages/insomnia-app/app/ui/redux/modules/global.js
packages/insomnia-app/package-lock.json
packages/insomnia-cookies/package-lock.json
packages/insomnia-importers/package-lock.json
packages/insomnia-libcurl/package-lock.json
packages/insomnia-xpath/package-lock.json
plugins/insomnia-plugin-cookie-jar/package-lock.json
plugins/insomnia-plugin-jsonpath/package-lock.json
plugins/insomnia-plugin-now/package-lock.json
plugins/insomnia-plugin-os/package-lock.json
plugins/insomnia-plugin-response/package-lock.json
plugins/insomnia-plugin-uuid/package-lock.json

Adds import from clipboard
Closes [#1748 ](https://github.com/getinsomnia/insomnia/issues/1748)

[Feature] Clipboard Feature

---

packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-enum.js
packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer.js

Support Enums in GraphQL documentation explorer

---

packages/insomnia-app/app/common/render.js

(Feature Request #1580) Merge Environment nested objects instead of overwrite them

[Feat Request 1580] Merge nested Environment objects

---

package-lock.json
package.json
packages/insomnia-app/.storybook/config.js
packages/insomnia-app/.storybook/index.less
packages/insomnia-app/.storybook/preview-head.html
packages/insomnia-app/.storybook/webpack.config.js
packages/insomnia-app/app/ui/components/base/copy-button.js
packages/insomnia-app/app/ui/components/base/editable.stories.js
packages/insomnia-app/app/ui/components/base/indeterminate-checkbox.js
packages/insomnia-app/app/ui/components/base/prompt-button.stories.js
packages/insomnia-app/app/ui/components/forms.stories.js
packages/insomnia-app/app/ui/components/gravatar-img.stories.js
packages/insomnia-app/app/ui/components/help-tooltip.stories.js
packages/insomnia-app/app/ui/components/notice.js
packages/insomnia-app/app/ui/components/notice.stories.js
packages/insomnia-app/app/ui/components/tooltip.stories.js
packages/insomnia-app/package-lock.json
packages/insomnia-app/package.json
plugins/insomnia-plugin-core-themes/index.js
plugins/insomnia-plugin-core-themes/themes/gruvbox.js

Starting a Storybook view for components. Insomnia doesn't really have many components for basic things like buttons, inputs, etc so this is the starting point that will help us start moving components out into a more standalone library. It will also be great for first-time contributors!

Add Storybook with basic components

---

package-lock.json
packages/insomnia-app/app/models/request-group.js
packages/insomnia-app/app/models/request.js
packages/insomnia-app/app/ui/containers/app.js
packages/insomnia-app/package-lock.json

Closes #1627 
This PR adds a prompt to set a custom name when duplicating requests and folders.

Prompt for name when duplicating requests and folders

---

packages/insomnia-app/app/models/settings.js
packages/insomnia-app/app/ui/components/editors/request-parameters-editor.js
packages/insomnia-app/app/ui/components/request-pane.js
packages/insomnia-app/app/ui/components/wrapper.js

This PR duplicates the bulk header editing functionality for query parameters

Ability to bulk-edit query parameters (Closes #1110)

---

packages/insomnia/src/common/constants.ts
packages/insomnia/src/utils/importers/importers/postman-2.0.types.ts
packages/insomnia/src/utils/importers/importers/postman-2.1.types.ts

chore: remove repetitive words
