app/common/prettify.js
Fix to handle of string JSON roots. Closes #170 
Not sure why the `i > 0` check was there before... This code was mostly copied from here originally https://github.com/zaach/jsonlint/blob/master/lib/formatter.js
=> Fixed spaces in JSON prettify

app/ui/components/base/file-input-button.js
- We do not want to clear the selected file if the file selection dialog is dismissed. 
N/A
This PR solves Issue #201 
**Related Issue**: #201
=> Will not clear selected file if dialog is dismissed

app/common/__tests__/render.test.js, app/common/render.js, app/templating/index.js, app/ui/components/modals/request-render-error-modal.js
This PR implements lazy rendering of Nunjucks tags. 
_beside the benefit discussed below, this is also required for request chaining (#210)_
When the environment contains a tag that throws an error, the request will fail to execute even if the variable is not referenced. This is because the entire environment is rendered on its own (to support recursive variables) before it's used to render the request. Here's an example:
```javascript
// environment
{
"broken": "{% badname %}"
}
```
The request will fail with a render error even if it does not contain `{{ broken }}`.
During the environment rendering phase, only render tags and not variables. Then, when rendering the request, render both variables and tags.
- `eg. {{ foo }} => {% uuid 'v4' %} => dd265685-16a3-4d76-a59c-e8264c16835a`
=> Implement lazy tag rendering

app/ui/components/tags/time-tag.js
Expanding to third decimal in Response Time Tag. Fixes #212
Provides more insight to the response time in milliseconds rather than rounding the first decimal.
=> Expanding Response Time tag to 3 decimals

webpack/webpack.config.development.babel.js
There has been some confusion around the development process. When the build server is started, it takes about 30 seconds for the initial build to complete (on decent hardware), leaving just a white screen. 
This change enables Webpack build logs to appear in the console, providing more details as to when the initial build finishes.
=> Show build info in console

LICENSE, README.md
Switch license from GPLv3 to AGPLv3.
From https://www.gnu.org/licenses/why-affero-gpl.html
> The GNU Affero General Public License is a modified version of the ordinary GNU GPL version 3. It has one added requirement: if you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there.
=> Switch license from GPL to AGPL

app/network/__tests__/network.test.js, app/network/network.js
This PR changes handling of set-cookie header from libcurl to [`tough-cookie`](https://github.com/salesforce/tough-cookie). 
Libcurl handles cookies too strictly. For example, it will ignore most cookies set on localhost.
This also fixes improper handling of the `host-only` attribute on libcurl cookies (it was backwards before)
Fixes #209
=> Switch from Curl to tough cookie to handle response cookies

app/ui/components/viewers/response-webview.js
This was a tricky one. When React calls the `ref` function during unmounting, `null` is passed to the function. This was a problem because, when `electron-context-menu` receives a falsy value, it applies itself globally (to all windows). A simple check to see if there was _actually_ a window fixed the issue.
Fixes #218
=> Fix adding context menu multiple times

app/network/o-auth-2/grant-password.js, app/ui/components/editors/environment-editor.js, app/ui/components/modals/workspace-environments-edit-modal.js, app/ui/components/request-pane.js, app/ui/components/response-pane.js, app/ui/css/components/environment-editor.less, app/ui/css/index.less
This change adds more visible errors to the environment editor. For example, if the JSON is invalid or variable names contain invalid characters like dashes or spaces.
Closes #144 
Errors now show up at the bottom of the editor.
Warnings still allow the environment to be saved, but it will inform the user of potential issues.
=> Better errors inside environment editors

app/network/o-auth-2/misc.js
This change makes the OAuth 2.0 window start a separate session every time the app is launched. Ideally, there should be a button somewhere to clear the session explicitly, but this should be good enough for now.
Closes #168
=> Start a fresh OAuth2 session every launch

app/analytics/index.js, app/models/settings.js, app/ui/components/settings/general.js
Closes #146
Added functionality to disable Google Analytics tracking.
Respect the privacy of users that do not want analytical information of their usage collected.
- Added a setting to the preference/settings modal 
- Added a disableAnalyticsTracking to the settings model
- If disableAnalyticsTracking is true, it will not complete the analytics initialization function
- An application restart would be required when disableAnalyticsTracking is changed. I don't see any added value of initializing or destroying the analytics tracking with the application running, and, follows most applications do (eg. Google Chrome). 
- trackEvent will still produce a console log when called, however, no request to Google Analytics is made
**Related Issue**: #146
=> Add setting to disable analytics tracking

app/ui/components/markdown-editor.js, app/ui/css/components/markdown-editor.less
This is a fix for the "bug" mentioned in https://github.com/getinsomnia/insomnia/pull/279#issuecomment-306885151
This change adds more styles for h[1-6] tags, and also disables HTML inside Markdown.
=> Markdown header styles and sanitize HTML

app/models/request-meta.js, app/ui/components/codemirror/code-editor.js, app/ui/components/response-pane.js, app/ui/components/viewers/response-viewer.js, app/ui/components/wrapper.js, app/ui/containers/app.js
Closes #273 
This PR adds a persistent response filter history and allows the user to select a previous item.
=> Track and display response filter history

app/common/misc.js, app/common/render.js, app/network/network.js, app/templating/base-extension.js, app/templating/extensions/__tests__/request-extension.test.js, app/templating/extensions/base-64-extension.js, app/templating/extensions/index.js, app/templating/extensions/now-extension.js, app/templating/extensions/request-extension.js, app/templating/extensions/response-extension.js, app/templating/extensions/timestamp-extension.js, app/templating/extensions/uuid-extension.js, app/templating/index.js, app/templating/utils.js, app/ui/components/codemirror/code-editor.js, app/ui/components/codemirror/extensions/autocomplete.js, app/ui/components/settings/plugins.js, app/ui/components/templating/tag-editor.js, app/ui/components/templating/variable-editor.js
Closes #275 
This PR adds a new `request` template tag for pulling values from the current request. This originated from the need to pull the value of a cookie for use as a CSRF header, for example.
=> New 'request' tag and a lot of improvements

app/network/network.js
Closes #297 
This PR adds a dynamic delay before making the request. The delay is however long it takes to ensure that `1000ms` have elapsed since the user's last keypress. This gives time for the app to flush all debounces and DB writes before making the request.
Since the max delay is `1000ms`, this may not catch everything on slower machines. A **correct** solution should be implemented in the future, but that would require much more work.
=> Hack-fix for stale requests being sent quickly after updating

app/common/misc.js, app/ui/components/base/file-input-button.js, app/ui/components/codemirror/one-line-editor.js, app/ui/components/dropdowns/content-type-dropdown.js, app/ui/components/editors/body/form-editor.js, app/ui/components/editors/body/url-encoded-editor.js, app/ui/components/key-value-editor/editor.js, app/ui/components/key-value-editor/row.js, app/ui/components/markdown-editor.js, app/ui/components/modals/code-prompt-modal.js, app/ui/components/modals/prompt-modal.js, app/ui/components/modals/request-create-modal.js, app/ui/components/settings/account.js, app/ui/components/settings/general.js, app/ui/components/settings/plugins.js, app/ui/components/wrapper.js, app/ui/containers/app.js, app/ui/css/components/forms.less, app/ui/css/components/key-value-editor.less, app/ui/css/components/markdown-editor.less, app/ui/css/editor/general.less, app/ui/css/layout/base.less
Closes #235 
Support multi-line text in both `multipart/form-data` and `x-www-form-urlencoded` request bodies.
Before, Insomnia's key-value component would strip newlines from values. This change adds a new multiline value type that will let the user edit the value in a multi-line text editing dialog instead.
=> Support multiline text in form data editors

app/models/index.js, app/models/request-version.js, app/models/response.js, app/package.json, app/ui/components/dropdowns/response-history-dropdown.js, app/ui/containers/app.js, package-lock.json, package.json
=> Track request versions and restore with response

app/network/__tests__/network.test.js, app/network/network.js
Closes #311 
This PR now handles `set-cookie` headers on every step of the redirect chain. Before, it would only handle the last step.
=> Set cookies on 30X redirects now

app/network/__tests__/certificate-url-parse.test.js, app/network/__tests__/url-matches-cert-host.test.js, app/network/certificate-url-parse.js, app/network/network.js, app/network/url-matches-cert-host.js, app/ui/components/modals/workspace-settings-modal.js
* Allow users to specify wildcards using `*` in certificate hosts.
* Wildcards can be added anywhere in the host string and multiple wildcards are supported.
Many organisations, including my own, use the same client certificate to authenticate against different deployments of the same API with altered host names (e.g `myservice.test.example.org`, `myservice.stage.example.org` and `myservice.example.org`). Allowing wildcards in the certificate host definition means that just one entry can be made for the certificate instead of three.
* When the user enters a client certificate host they can include wildcards using `*`.
I've extracted the certificate matching logic into two files. I decided to keep their tests in separate files as well since there needed to be quite a lot of scenarios to …
=> Allow wildcards in client certificate hosts

app/models/environment.js, app/ui/components/base/dropdown/dropdown-item.js, app/ui/components/base/editable.js, app/ui/components/codemirror/extensions/autocomplete.js, app/ui/components/dropdowns/environments-dropdown.js, app/ui/components/modals/workspace-environments-edit-modal.js, app/ui/css/components/sidebar.less, app/ui/css/layout/base.less
This adds the ability to color-code environments, which is useful for knowing which one is active. 
It also modified the sidebar styles to be more useful at small sizes. Before, the buttons used to be 50/50. Now, the flex to fit the space depending on how much text is in the buttons, and wrap to two lines if there isn't enough space (cookies button used to disappear at small sizes).
=> Add ability to assign color to environments

app/__mocks__/electron.js, app/common/database.js, app/common/misc.js, app/models/__tests__/response.test.js, app/models/index.js, app/models/request-version.js, app/models/response.js, app/network/__tests__/network.test.js, app/network/network.js, app/templating/base-extension.js, app/templating/extensions/__tests__/response-extension.test.js, app/templating/extensions/response-extension.js, app/ui/components/dropdowns/environments-dropdown.js, app/ui/components/response-pane.js, app/ui/components/tooltip.js, app/ui/components/viewers/response-viewer.js, app/ui/containers/app.js
Since Insomnia uses an in-memory database, large response bodies caused big problems.
1. Responses needed to be kept in memory always (leading to high RAM usage)
2. Had no way of loading response details from DB without retrieving the body too
3. Caused NeDB to crash when response DB totaled more than NodeJS's 256MB string size limit.
=> Move response bodies out of DB

app/network/o-auth-2/refresh-token.js
Issue:
- In request "Auth" - "OAuth 2.0" - "Refresh Token" button throws error "Failed to Fetch" when no protocol in access_token url.
Reason:
- window.fetch(url, ..) url parameter wasn't getting check and added if no protocol so add  setDefaultProtocol like access_token.js uses.
=> Fixed OAuth 2.0 Refresh Token

app/datasets/content-types.js
Adds the JSON API mimetype to the list of content types.
~~It should allow syntax highlighting in the request body to work properly when this mimetype is used as the Content-Type.~~ (I just realized that this was a separate issue caused by something else.)
Allows it to appear as a suggestion in the autosuggest list for Content-Type.
=> Add JSON API mimetype to content types

app/common/__tests__/render.test.js, app/common/render.js, app/templating/base-extension.js, app/templating/extensions/request-extension.js, app/templating/index.js, app/ui/components/settings/plugins.js, app/ui/components/templating/tag-editor.js, app/ui/components/templating/variable-editor.js, app/ui/containers/app.js
This PR makes a few changes and fixes to the render pipeline to address some bugs and improve usability.
- Render consists of two phases (build and render environment, render request)
- Metadata like active request/workspace didn't used to be passed to first stage
- used to do it by only rendering variables when rendering environment initially
- now do it by trying to render environment variables and leaving them as-is if exception thrown
- these exceptions will re-emerge at the second stage if the variable is actually used
- this also addresses the case where a variable was set to a tag, then used in a filter (Fixes #350)
=> Environment Rendering Improvements

app/common/constants.js, app/models/request.js, app/network/__tests__/network.test.js, app/network/network.js, app/ui/components/dropdowns/auth-dropdown.js, app/ui/components/editors/auth/auth-wrapper.js, app/ui/components/editors/auth/aws-auth.js, package.json
* Add AWS Auth type support (Closes #344)
* [Screenshots here](http://imgur.com/a/9igw0)
* Multifactor authentication (MFA) not yet supported
Allow end users to easily send requests to Amazon Web Services APIs. Although this authentication scheme is non-standard, the service is widely used and difficult to use without good support from developer tools.
Follows closely existing patterns for other authentication schemes.
More work would be required to support Multifactor authentication, which requires an additional field AWS_SESSION_TOKEN. I can do that as well but would like your guidance on the UI.
**Related Issue**: #344
=> Add support for AWS authentication

app/common/database.js, app/models/response.js, app/ui/components/dropdowns/response-history-dropdown.js, app/ui/components/markdown-preview.js, app/ui/components/response-pane.js, app/ui/components/wrapper.js, app/ui/containers/app.js, app/ui/redux/modules/index.js, app/ui/redux/selectors.js
Now that we have response bodies out of the local DB (#338) we can now keep response objects in Redux without worrying about taking up memory. Before, response bodies were looked up on demand, which was really clunky and bad.
=> Move Response objects into Redux

app/ui/components/modals/request-switcher-modal.js
- Makes `searchString` a little more forgiving
- Allows matching of multiple ordered substrings in request names without having to type everything between substrings.
- For example, if you have a request called `(Payments) Refund charges for specific account` you may search for `p refund account` to find such request.
N/A
I originally tried a more algorithmic approach of traversing both string to figure out if the `searchString` characters exist in order in the `matchedRequests` strings but this was significantly slower than constructing and using a regular expression (18ms vs. 1ms per `matchedRequest`)
**Related Issue**: N/A
=> Allow fuzzy searching in Quick Switch modal

app/main.development.js, app/ui/redux/create.js, package-lock.json, package.json
* Automatically tries to install and load react and redux extensions when running in dev mode.
* Makes things more inviting to new developers.
Added a dev dependency of `electron-devtools-installer` and modified `app/ui/redux/create` to add standard boilerplate Redux DevTools support if `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` is present.
Redux DevTools are awesome! 👍
=> Adding react and redux dev tools

app/common/fetch.js, app/sync/index.js
_This is a better attempt at #380_
Currently, the sync operation is ran every `15` seconds even if it longer than that. 
- `nextSyncTime = 15 + TIME_IT_TOOK_TO_SYNC_LAST_TIME * 2`
=> Throttle sync when slow

app/network/o-auth-2/grant-authorization-code.js
Made a change to how the regex used to detect the `finalUrl` during the OAuth2 flow.
Keycloak is an  an OAuth2/OpenId Connect authentication provider. As part of Keycloak's authentication flow it loads several pages in order to prompt the user for different pieces of information. One of these pages is an internal keycloak page with a `code=12341234` at the end of the url. 
This triggers the regex and Insomnia will extract this invalid code and attempt to get a token. The access token request fails because the code is internal to keycloak and isn't actually an authorization code.
This PR will add the redirect uri, if present, to the regex so that it will only trigger if the url loaded in the window begins with the redirect uri.
Not sure if RegEx is commonly available. Don't normally …
=> Add redirectUri to url regex for OAuth2

app/sync/storage.js, app/ui/components/codemirror/base-imports.js, app/ui/components/codemirror/code-editor.js, app/ui/components/dropdowns/sync-dropdown.js, app/ui/components/response-timer.js
This PR addresses some of the most obvious performance issues.
- Added event listener to DB to watch for changes instead of polling
=> Address some obvious performance wins

app/ui/components/editors/body/body-editor.js, app/ui/components/editors/body/graph-ql-editor.js, app/ui/components/request-pane.js, app/ui/components/wrapper.js
Currently, GraphQL introspection queries (to fetch the schema) are sent with the HTML5 fetch API. This means that a lot of Insomnia features like auth, proxy settings, and cookies are not sent. This PR moves the introspection query from fetch to libcurl by using the same code path as sending reqular requests.
=> Move GraphQL introspection requests to Insomnia network stack

app/network/authentication.js, app/ui/components/editors/auth/o-auth-2-auth.js, app/ui/css/layout/base.less
Closes #419 
Before, Insomnia added `Authorization: Bearer <MY_OAUTH_TOKEN>` with requests. However, some servers expect a different name for this, so this PR adds the ability to override the default `Bearer` prefix with something else.
This PR also moves some of the advanced OAuth2 options into a collapsed-by-default section.
=> Add ability to specify OAuth 2 Authorization header prefix

app/network/network.js, app/plugins/context/__tests__/request.test.js, app/plugins/context/request.js, app/plugins/install.js
As discussed in slack: <https://getinsomnia.slack.com/archives/C4Z8M9E86/p1502912037000177>, this pr intended to add these features:
- Allow plugin to access current context, so plugin's can get environment data now.
- Add getAllHeaders API for context request
With these improves:
- Use JSON to parse `npm show`'s output, it's indeed a JSON content, we don't need to parse it with split in `\n`.
=> Add environment to plugin

app/ui/components/templating/tag-editor.js
This PR adds the Request Method to the Request Select Field in the Tag Editor to see the difference between calls with different methods but same urls.
=> [Improvement] Add Method to Tag Editor Request Select Field

.flowconfig
The .flowconfig file had an empty line at the start which causes the following issue when running the "npm test:flow" command:
{"code":8,"reason":"Invalid_flowconfig","msg":".flowconfig:1 Unexpected config line not in any section"}
Removing the first line fixed the error on my system:
Microsoft Windows 10 Pro Build 15063
Node v8.6.0
Flow 0.55.0
=> Fix Invalid_flowconfig error

.gitattributes, .gitignore
Upon cloning this repository with my windows git client the line endings of text files were converted from LF to CRLF. This causes the unit tests in prettify.test.js and a test in network.test.js to fail, since they expect LF line endings. This commit prevents git clients form converting the line endings in some test fixture files.
I guess the git client in the appveyor windows image doesn't automatically convert line endings and thus doesn't have this issue.
=> Fixed running unit tests under Windows

app/__tests__/package.test.js, app/analytics/index.js, app/network/__tests__/multipart.test.js, app/network/__tests__/network.test.js, app/network/multipart.js, app/network/network.js, app/package.json, app/ui/components/pdf-viewer.js, app/ui/components/response-pane.js, app/ui/components/viewers/response-viewer.js, flow-typed/form-data.js, flow-typed/pdfjs-dist.js, package-lock.json, package.json
The old `simple-react-pdf` component stopped working when we upgraded to React 16. It also didn't support a few things like retina rendering, web workers, and re-rendering on window resize. 
Ooops, it looks like the multipart fixes also ended up in here.
=> Rewrite broken PDF viewer

app/common/misc.js, app/ui/components/base/link.js, app/ui/components/base/mailto.js, app/ui/components/error-boundary.js, app/ui/components/modals/error-modal.js, app/ui/components/modals/settings-modal.js, app/ui/components/request-pane.js, app/ui/components/response-pane.js, app/ui/components/viewers/response-headers-viewer.js, app/ui/components/wrapper.js, app/ui/containers/app.js, app/ui/css/layout/base.less
Now, render failures won't take down the whole app.
For generic broad errors, we will pop an alert when they fail. And, for more specific errors, we will render custom UI to display them.
=> Added error boundaries for better failures

app/common/prettify.js, app/ui/components/editors/body/graph-ql-editor.js, package-lock.json, package.json
Closes #549
Before, Insomnia did not pass `operationName` with queries. Now, it will pass the first named query if there is one. 
Note: There is still no way for the user to specify an `operationName` explicitly if there are more than one.
P.S. This change also leaves out the `variables` param if it is not set.
=> Support basic operationName for GraphQL

app/models/__tests__/workspace.test.js, app/models/client-certificate.js, app/models/environment.js, app/models/index.js, app/models/workspace.js, app/network/__tests__/network.test.js, app/network/network.js, app/sync/index.js, app/ui/components/modals/workspace-settings-modal.js, app/ui/components/wrapper.js, app/ui/containers/app.js, app/ui/css/constants/dimensions.less, app/ui/index.js, app/ui/redux/modules/index.js, app/ui/redux/selectors.js
=> New ClientCertificate model and ability to have private certificates

app/network/__tests__/certificate-url-parse.test.js, app/network/__tests__/url-matches-cert-host.test.js, app/network/certificate-url-parse.js, app/network/url-matches-cert-host.js
Closes #564 
This PR implements glob matching on port for client certificates so it is now possible to match something that looks like this: `https://localhost:*` or even `https://localhost:3*`.
=> Client certificate glob matching on port

app/common/render.js, app/models/cookie-jar.js, app/network/network.js, app/network/o-auth-2/__tests__/grant-authorization-code.test.js, app/network/o-auth-2/__tests__/grant-client-credentials.test.js, app/network/o-auth-2/__tests__/grant-password.test.js, app/network/o-auth-2/get-token.js, app/network/o-auth-2/grant-authorization-code.js, app/network/o-auth-2/grant-client-credentials.js, app/network/o-auth-2/grant-implicit.js, app/network/o-auth-2/grant-password.js, app/network/o-auth-2/refresh-token.js, app/ui/components/editors/body/graph-ql-editor.js
Closes #580 
This PR changes the OAuth 2.0 handlers to use the Insomnia network stack instead of `window.fetch`. This means that the current requests parameters and settings (eg. proxy, ssl validation, etc) will be used to fetch OAuth tokens.
=> Use Insomnia network stack for OAuth 2.0 requests

app/common/constants.js, app/ui/components/modals/wrapper-modal.js, app/ui/components/request-pane.js, app/ui/components/response-pane.js, app/ui/components/viewers/response-headers-viewer.js, app/ui/components/viewers/response-multipart.js, app/ui/components/viewers/response-viewer.js, app/ui/components/wrapper.js, app/ui/css/components/modal.less, flow-typed/moment.js, flow-typed/multiparty.js, package-lock.json, package.json
Closes #589 
This PR adds a new multipart response viewer, allowing to view each part at a time. You can also save each part to the filesystem or view its headers.
=> Add new multipart response viewer

app/__mocks__/insomnia-node-libcurl.js, app/common/misc.js, app/models/environment.js, app/models/response.js, app/network/__tests__/network.test.js, app/network/network.js, app/ui/components/settings/general.js, flow-typed/insomnia-node-libcurl.js
Closes #588 
This PR disables `node-libcurl`'s header parsing and brings it in-house. This gives Insomnia more accurate header results like providing the ability to show multiple headers with the same name.
=> Custom headers parsing

app/__mocks__/electron.js, app/common/database.js, app/main.development.js, app/models/response.js, app/ui/components/request-pane.js, flow-typed/electron.js
Right now, the architecture of Insomnia is essentially a web app that runs in an Electron window. Everything happens in the browser window: network requests, database operations, data sync, encryption.
This is bad for a number of reasons:
- DB does not support multi-process which prevents Insomnia from supporting multi-window
- Sync and encryption is CPU intensive so will slow down the UI
- Many other things related to the prevention of a good multi-window experience
This PR moves the initialization and communication with the DB into the main process. This is then communicated with via Electron's inter-process communication API.
=> Move Database to Electron Main Process

app/ui/components/response-timer.js
I was slightly bothered by the request timer jumping because it was reducing its precision when it reached `.0`. I therefore propose to always call `toFixed(1)` on it for a nicer look.
=> Always show request timer with one decimal precision

app/common/analytics.js, app/common/misc.js, app/main.development.js, app/models/stats.js, app/package.json, app/sync/session.js, app/ui/components/base/link.js, app/ui/components/check-for-updates-button.js, app/ui/components/settings/general.js, app/ui/components/toast.js, app/ui/containers/app.js, flow-typed/electron-squirrel-startup.js, flow-typed/electron.js
Closes #485 
In a previous commit, the changelog dialog was removed but I forgot to add a new mechanism to display that the app was updated. This PR adds that mechanism and also moves stats tracking and handling to the `main` process.
If the application launches to a new version, a subtle notification will be displayed instead of an intrusive modal dialog.
=> Better stats handling and update notifications

packages/insomnia-app/app/common/__tests__/render.test.js, packages/insomnia-app/app/common/render.js, packages/insomnia-app/app/network/network.js, packages/insomnia-app/app/plugins/context/__tests__/app.test.js, packages/insomnia-app/app/plugins/context/__tests__/request.test.js, packages/insomnia-app/app/plugins/context/__tests__/response.test.js, packages/insomnia-app/app/plugins/context/app.js, packages/insomnia-app/app/plugins/context/data.js, packages/insomnia-app/app/plugins/context/request.js, packages/insomnia-app/app/plugins/context/response.js, packages/insomnia-app/app/plugins/index.js, packages/insomnia-app/app/templating/base-extension.js, packages/insomnia-app/app/templating/extensions/index.js, packages/insomnia-app/app/templating/index.js, packages/insomnia-app/app/ui/components/modals/prompt-modal.js, packages/insomnia-app/app/ui/components/templating/tag-editor.js, packages/insomnia-app/package.json, plugins/insomnia-plugin-prompt/README.md, plugins/insomnia-plugin-prompt/index.js, plugins/insomnia-plugin-prompt/package.json
This PR introduces a new template tag that can be used to prompt the user for input before a request (useful for sensitive info).
To-Do:
=> Prompt Template Tag and Plugin arg validation

packages/insomnia-app/app/network/o-auth-2/constants.js, packages/insomnia-app/app/network/o-auth-2/get-token.js, packages/insomnia-app/app/network/o-auth-2/grant-client-credentials.js, packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
This PR adds an optional field "audience", used in OAuth 2 client credentials authorization flow. [Auth0](https://auth0.com/docs/api/authentication#client-credentials) (and others I'm sure) uses this field to specify which target API you want to access. The tooltip message is taken from [the RFC](https://tools.ietf.org/html/draft-tschofenig-oauth-audience-00) abstract section.
Closes #678
=> Add audience field for oauth2 client credentials

packages/insomnia-app/.electronbuilder, packages/insomnia-app/package.json
Closes #354 
Hi! I put together this PR to add a [snap](https://snapcraft.io) package. I've tested it on Ubuntu 18.04 (daily), 17.10 and 16.04, but it should work just as well on Ubuntu 14.04, Linux Mint, Manjaro, Debian, OpenSUSE, Solus, etc.
If you merge and `npm run package` from `packages/insomnia-app/` it will create `dist/insomnia_5.12.4_amd64.snap`.
Copy this to a Linux system, [enable snap support](https://docs.snapcraft.io/core/install), then run:
`sudo snap install --dangerous insomnia_5.12.4_amd64.snap`
Run with `insomnia` or find it in the launcher.
If you create a developer account and push this to the Snap Store, it can be discovered and installed through GNOME Software and https://snapcraft.io/discover. To create the developer account, [sign up …
=> Add snap package. https://snapcraft.io

packages/insomnia-app/app/common/import.js, packages/insomnia-app/app/ui/components/wrapper.js, packages/insomnia-importers/index.js, packages/insomnia-importers/src/__tests__/fixtures.test.js, packages/insomnia-importers/src/__tests__/import-errors.test.js, packages/insomnia-importers/src/cli.js
Adds support for asynchrous (Promise-based) importers.  It's dependency for the swagger2 importer sent in another PR (https://github.com/getinsomnia/insomnia/pull/695).
=> Support for async importers

packages/insomnia-app/app/models/request.js, packages/insomnia-app/app/network/__tests__/authentication.test.js, packages/insomnia-app/app/network/o-auth-1/constants.js, packages/insomnia-app/app/network/o-auth-1/get-token.js, packages/insomnia-app/app/ui/components/editors/auth/o-auth-1-auth.js, packages/insomnia-app/flow-typed/oauth-1.0a.js
Attempts to close #606 but isn't quite there.
I took stab at #606, couldn't wrap my head around rendering on events (ie. hiding the privateKey input until the correct dropdown is selected) so I tried to get the basics of just a key input box to render and now I get `Render Failure: CodeEditor is not defined` whenever I try to access the OAuth 1 menu. Obviously this should not be merged as is, because it completely breaks the OAuth 1 UI, but maybe I can get some assistance?
As far as the actual logic for RSA_SHA1 goes, I think it should work but I haven't been able to test it because I've broken the UI 👍
=> Add RSA-SHA1 signing to OAuth 1.0

packages/insomnia-importers/README.md
Reasons for the changes:
* The output format of the importer is Insomnia v3 now and it also imports from Insomnia v2.
* Be more precise on the Postman version, because only v2.0 and not v2.1 is supported.
Thank you for the standalone and open source importer project. It helps me to convert the cURL output of Spring REST Docs to Insomnia (and Postman), see https://github.com/fbenz/restdocs-to-postman.
=> Update insomnia-importers README

packages/insomnia-app/app/ui/components/dropdowns/response-history-dropdown.js, packages/insomnia-app/app/ui/components/tags/url-tag.js
=> Replace time and size with URL in history dropdown (#677)

packages/insomnia-app/app/ui/components/codemirror/code-editor.js, packages/insomnia-app/app/ui/components/editors/body/body-editor.js, packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js, packages/insomnia-app/app/ui/components/editors/body/raw-editor.js, packages/insomnia-app/app/ui/components/response-pane.js, packages/insomnia-app/app/ui/components/viewers/response-viewer.js
Closes #736 
This PR adds functionality to `CodeEditor` to save and restore editor state based on a `uniquenessKey` passed into the component.
What this applies to:
- Request body text modes (JSON, XML, etc)
- GraphQL editor
- Response preview
This PR also removes the editor "flash" that happened when switching requests. Now, instead of creating a new Codemirror instance every time, it reuses the old one.
=> Persist editor scroll positions

packages/insomnia-app/app/ui/components/editors/request-headers-editor.js
When I create a header, it has "New My-Header" for the placeholder:
This is a bit redundant. I think "My-Header" or "New Header" would both be good, but since the value is "New Value", I think it makes sense to change it to "New Header". Here's what it looks like after the change in this PR:
=> change header placeholder from My-Header to Header so it says New Header

packages/insomnia-app/app/models/request.js, packages/insomnia-app/app/network/authentication.js, packages/insomnia-app/app/ui/components/editors/auth/asap-auth.js
PR adds field in ASAP Auth to supply additional JWT claims beyond those already required/available.
=> Add support for additional claims in ASAP Auth

packages/insomnia-app/app/ui/css/components/query-editor.less
Closes #869.
This is the most simple solution that does not have a negative impact on user experience in my test. With this simple CSS change the height of the query preview box appears as normal if empty and will automatically expand to fit the length of the query which is ideal for longer queries.
A more robust solution would allow the user to expand and shrink the box at will. However I don't feel that would be ideal for the user experience because it adds an extra moving part when the box can resize on it's own very easily and the container itself is scrollable.
=> Height of the query preview box is not constrained for longer query strings

packages/insomnia-app/app/ui/redux/modules/global.js
The Swagger importer also supports parsing a spec in YAML format.
=> Allow YAML extensions in file selection import dialog too

packages/insomnia-app/app/plugins/context/__tests__/response.test.js, packages/insomnia-app/app/plugins/context/response.js, packages/insomnia-app/app/plugins/index.js
This PR adds a `setBody()` method to the response API within plugin hooks. 
Now, it is possible for plugins to modify the response body for things like formatting, sanitizing, filtering, etc. Since there is no way to tell that the plugin modified the response, this isn't the best user experience. However, it's been requested multiple times so it's finally here!
Here's an example of what you can do with it:
```js
module.exports = [
context => {
// Get the response body
const root = JSON.parse(context.response.getBody());
// Wrap body in a base object
const newRoot = {root: root};
// Re-stringify
const newBody = JSON.stringify(newRoot);
// Replace body with wrapped one
context.response.setBody(Buffer.from(newBody));
}
];
```
=> Add setBody() to response plugin API

packages/insomnia-app/app/common/__tests__/database.test.js, packages/insomnia-app/app/common/render.js, packages/insomnia-app/app/models/__tests__/request.test.js, packages/insomnia-app/app/models/request.js, packages/insomnia-app/app/network/network.js, packages/insomnia-app/app/plugins/context/__tests__/data.test.js, packages/insomnia-app/app/ui/components/codemirror/code-editor.js, packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js, packages/insomnia-app/app/ui/components/modals/wrapper-modal.js, packages/insomnia-app/app/ui/css/components/forms.less
Closes #965
This PR lets the user view the introspection request/response timeline when an error occurs.
=> Add ability to view introspection request/response timeline upon error

packages/insomnia-app/app/templating/base-extension.js, packages/insomnia-app/app/ui/components/templating/tag-editor.js, packages/insomnia-app/package.json, plugins/insomnia-plugin-request/index.js, plugins/insomnia-plugin-request/package.json
Closes #971 
This PR extends the _Request_ template tag to add `name` and `folder` options.
=> Add name and folder options to Request tag

packages/insomnia-app/app/network/o-auth-2/__tests__/grant-implicit.test.js, packages/insomnia-app/app/network/o-auth-2/get-token.js, packages/insomnia-app/app/network/o-auth-2/grant-implicit.js, packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
Since most of the work was done when `audience` was added to the `client-credentials` grant type I just had to add the field to `implicit`.
This should take care of #1008
=> add audience param to implicit Oauth grant

packages/insomnia-app/app/models/settings.js, packages/insomnia-app/app/ui/components/dropdowns/environments-dropdown.js, packages/insomnia-app/app/ui/components/settings/general.js, packages/insomnia-app/app/ui/components/sidebar/sidebar.js, packages/insomnia-app/app/ui/components/wrapper.js
Add a bar color indicator along with new a setting to choose whether to use the original dot or the new bar.
Closes #995
=> Add bar color indicator for environments

packages/insomnia-httpsnippet/src/index.js
Closes #1189
Tracked this bug down to be an issue with using util._extend which appears to have stability issues and reversed the order of the attributes in the object created. In the Node docs there is a note about the method being deprecated. I have taken the suggested action of replacing the call with Object.assign. I took the opportunity to change all other occurrences of this method call in the file at the same time.
=> Fix reversed query string parameters in code generation

packages/insomnia-httpsnippet/src/targets/python/requests.js
Closes #1188
Currently the code generation with Python Requests is missing out query string variables specifed in the URL string
New code fixes this and confirm it works with both query strings specified in URL and in query section editor
=> Fix Python Requests Code generation

packages/insomnia-importers/src/importers/swagger2.js
In swagger files you can specify parameters for a path.
Insomnia added this parameters as methods. This simply filters this "parameters methods"
=> filter "parameters method" from swagger imports

README.md
I created a plugin for adding default query parameters and headers (and hopefully more things in the future, hence the un-specific name for the plugin, and re-implementation of default headers). This PR adds this plugin to the README.
https://github.com/wwselleck/insomnia-plugin-defaults
=> [Documentation] Add insomnia-plugin-defaults to README.md

packages/insomnia-app/app/common/constants.js, packages/insomnia-app/app/common/database.js, packages/insomnia-app/app/common/misc.js, packages/insomnia-app/app/main/window-utils.js, packages/insomnia-app/app/models/__tests__/response.test.js, packages/insomnia-app/app/models/response.js, packages/insomnia-app/app/network/network.js, packages/insomnia-app/app/sync/storage.js
I have added a utility function to misc.js to allow the data directory to be set via an environment variable called INSOMNIA_DATA_PATH. I did not change anything with regards to the temp directory.
=> Closes 1225

packages/insomnia-app/app/templating/extensions/index.js, packages/insomnia-app/app/ui/components/base/file-input-button.js, packages/insomnia-app/app/ui/components/templating/tag-editor.js
I've added support for the file input to have a file type filter applied as well as the ability to select directories if allowed.
Reasoning for this is to provide plugins the ability to have more complex capabilities such as looping through files in a directory or only allowing certain files to be selected.
Possible improvements would be to also allow option of multiple files to be selected.
=> [Re-Submitted] Added support for file extension filtering as well as ability to select a directory to file picker dialog

packages/insomnia-app/app/main/window-utils.js
fix  about menu  shell : undefined
=> fix  about menu  shell : undefined

packages/insomnia-app/app/common/hotkeys.js, packages/insomnia-app/app/ui/components/settings/shortcuts.js, packages/insomnia-app/app/ui/components/viewers/response-raw.js, packages/insomnia-app/app/ui/components/viewers/response-viewer.js
Closes: #737
I added a keyboard shortcut `Ctrl+'` that will set focus on `ResponseViewer` in `ResponsePane` and select all the text in it. Currently the supported view modes are `Visual Preview` for responses that are rendered as source (unlike CSV and image), `Source Code`, and `Raw Data`.
This is useful to quickly copy and paste responses of types JSON, XML, and raw formats without user clicking the response pane.
I think using `Ctrl+'` would suit well with `Ctrl+;` to focus on `BodyViewer` in `RequestPane` which may be added in the future :smile:.
=> Add keyboard shortcut to focus on response viewer

packages/insomnia-app/app/ui/components/templating/tag-editor.js
Closes: #1286 
Added all the folders (request groups) names as prefix in tag editor dialog drop down.
Request list
Dropdown
=> Display all request groups names in tag editor drop down

plugins/insomnia-plugin-request/__tests__/index.test.js, plugins/insomnia-plugin-request/index.js
=> Implement query parameter tag and test (#1112)

packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js, packages/insomnia-app/app/ui/components/markdown-editor.js, packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.js, packages/insomnia-app/app/ui/components/modals/settings-modal.js, packages/insomnia-app/app/ui/components/modals/workspace-settings-modal.js, packages/insomnia-app/app/ui/components/request-pane.js, packages/insomnia-app/app/ui/components/response-pane.js, packages/insomnia-app/app/ui/css/components/tabs.less
Closes #1299 .
Before change (focused on Overview tab via keyboard):
After change:
The tab is only highlighted when focused via the keyboard, else it appears as it does with current implementation.
=> Highlight focused keyboard tab (#1299)

packages/insomnia-app/app/ui/components/codemirror/code-editor.js, packages/insomnia-app/app/ui/components/response-pane.js, packages/insomnia-app/app/ui/components/viewers/response-viewer.js
Closes: #1031
I added response pane tab select listener, then trigger CodeMirror editor refresh when it is selected. For the editor to be able to be refreshed it must be visible; but since the tab selection listener is triggered right before that, I used `process.nextTick()` to do the refresh.
I also removed a seemingly duplicate line that registers the same callback to CodeMirror, which causes the callback to be called twice everytime the editor's value is changed.
=> Refresh CodeMirror editor when focused, and remove duplicate listener

packages/insomnia-app/app/network/o-auth-2/get-token.js, packages/insomnia-app/app/network/o-auth-2/refresh-token.js
This PR will allow Insomnia to re-authenticate again to get brand new access and refresh tokens when the refresh token request fails due an unauthorized request. This happens when the backend rejects the refresh token for some reason, like refresh token expiration.
This is an opinionated implementation, which means that this behavior is not configurable. @gschier let me know if an option to configure this behavior is necessary.
- Closes #849
=> Fetch new access and refresh tokens when refresh fails

packages/insomnia-app/app/common/har.js, packages/insomnia-app/app/network/__tests__/authentication.test.js, packages/insomnia-app/app/network/authentication.js, packages/insomnia-app/app/network/network.js, packages/insomnia-app/app/ui/components/editors/auth/hawk-auth.js
Closes #1321 
This change let's a user select whether Hawk Auth should use Payload Validation or not ). In terms of changes to the UI, it adds an additional checkbox to the Hawk Auth tab (which is off by default). I was a little unsure about the change I made to the signature of `getAuthHeader` so if there's a better way to get at the body and the content type without passing the whole request in let me know and I can adjust this.
=> Add ability to optionally use Hawk payload validation.

packages/insomnia-httpsnippet/src/targets/javascript/fetch.js, packages/insomnia-httpsnippet/src/targets/javascript/index.js, packages/insomnia-httpsnippet/src/targets/javascript/jquery.js, packages/insomnia-httpsnippet/test/fixtures/available-targets.json, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/application-form-encoded.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/application-json.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/cookies.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/custom-method.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/full.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/headers.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/https.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/multipart-data.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/multipart-file.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/multipart-form-data.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/query.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/short.js, packages/insomnia-httpsnippet/test/fixtures/output/javascript/fetch/text-plain.js, packages/insomnia-httpsnippet/test/targets/javascript/fetch.js
Closes #1313
Add simple JavaScript Fetch snippet with ES6 syntax.
=> Fetch JS snippet

package-lock.json, packages/insomnia-app/app/common/constants.js, packages/insomnia-app/app/common/hotkeys-listener.js, packages/insomnia-app/app/common/hotkeys.js, packages/insomnia-app/app/models/settings.js, packages/insomnia-app/app/ui/components/base/dropdown/dropdown-hint.js, packages/insomnia-app/app/ui/components/base/dropdown/dropdown.js, packages/insomnia-app/app/ui/components/base/modal.js, packages/insomnia-app/app/ui/components/dropdowns/environments-dropdown.js, packages/insomnia-app/app/ui/components/dropdowns/request-actions-dropdown.js, packages/insomnia-app/app/ui/components/dropdowns/request-group-actions-dropdown.js, packages/insomnia-app/app/ui/components/dropdowns/response-history-dropdown.js, packages/insomnia-app/app/ui/components/dropdowns/workspace-dropdown.js, packages/insomnia-app/app/ui/components/hotkey.js, packages/insomnia-app/app/ui/components/modals/settings-modal.js, packages/insomnia-app/app/ui/components/request-pane.js, packages/insomnia-app/app/ui/components/request-url-bar.js, packages/insomnia-app/app/ui/components/response-pane.js, packages/insomnia-app/app/ui/components/settings/shortcuts.js, packages/insomnia-app/app/ui/components/sidebar/sidebar-children.js, packages/insomnia-app/app/ui/components/sidebar/sidebar-filter.js, packages/insomnia-app/app/ui/components/sidebar/sidebar-request-group-row.js, packages/insomnia-app/app/ui/components/sidebar/sidebar-request-row.js, packages/insomnia-app/app/ui/components/sidebar/sidebar.js, packages/insomnia-app/app/ui/components/viewers/response-viewer.js, packages/insomnia-app/app/ui/components/wrapper.js, packages/insomnia-app/app/ui/containers/app.js, packages/insomnia-app/package-lock.json
Partially closes: #1162 
This PR is the first one to enable customizable key bindings feature. I plan to submit 1-2 more PRs, so that it will be easier to review, as there could be many additions and changes.
In this PR:
- New data models for hotkeys, with the separation of key combinations by OSes (mac, win, and linux). The models and namings are loosely inspired by those of VS Code's.
- Save key bindings in DB, in `settings` model.
- Give each hotkeys an `id`, the style is similar to that of VS Code's; except that this one uses `_` instead of `.`, e.g., `request_showSettings` instead of `request.showSettings`. The reason is that NeDB prohibits naming fields with `.`.
- Use `⌥` symbol for Mac's option key, previously was `^` (is this intended?).
- Some codes' styles are changing, like …
=> New data models for hotkeys and store the key bindings in settings

plugins/insomnia-plugin-base64/__tests__/index.test.js, plugins/insomnia-plugin-base64/index.js, plugins/insomnia-plugin-base64/package.json
This small and dirty change adds support for Base64url encoding & decoding.
I had only one concern though, when I intentionally broke the test, npm test was still returning successfully, so not really sure what's going on with that...
=> Add support for Base64url encoding (#1348)

packages/insomnia-app/app/common/constants.js, packages/insomnia-app/app/ui/components/codemirror/code-editor.js, packages/insomnia-app/app/ui/components/settings/general.js
Closes #208 (Currently closed, but the bug still exists)
This fixes the issue regarding the modal closing when `Escape` key is pressed in vim mode. CodeMirror has an event `keyHandled`, which can be used to stop the `Escape` event from closing the modal.
https://codemirror.net/doc/manual.html#event_keyHandled
=> Prevent modal closing for vim mode

packages/insomnia-importers/index.js, packages/insomnia-importers/package-lock.json, packages/insomnia-importers/package.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/dereferenced-input.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/dereferenced-output.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/dereferenced-with-tags-input.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/dereferenced-with-tags-output.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-input.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-output.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-with-tags-input.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-with-tags-output.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-yml-input.yml, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-yml-output.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-yml-with-tags-input.yml, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-yml-with-tags-output.json, packages/insomnia-importers/src/__tests__/utils.test.js, packages/insomnia-importers/src/importers/openapi3.js, packages/insomnia-importers/src/importers/swagger2.js, packages/insomnia-importers/src/importers/swagger3.js, packages/insomnia-importers/src/utils.js
Hi! 👋 
The issue over at #281 was a catch-all for Swagger/OpenAPI, and some folks were after OpenAPI v3 support. This PR addresses that.
This PR doesn't try to implement the complete spec at all, but it _does_ do the bulk of the work for the import. I'd consider it complete at a functional level, and we could accept future PRs for enhancements. Open to suggestion though :)
As this is a first step, I based my development on the exist fixtures. My testing strategy was to convert swagger2 test input to openapi3, and use the same outputs for verification. I did that via:
- open http://editor.swagger.io/
- paste existing swagger2 test `-input` file
- (transform JSON->YAML when asked, if necessary)
- `Edit` > `Convert to OpenAPI 3`
- export (as JSON or YAML, depending on existing test)
So, with …
=> OpenAPI v3 importer

packages/insomnia-app/app/network/o-auth-2/constants.js, packages/insomnia-app/app/network/o-auth-2/grant-implicit.js
This adds the final missing piece for being able to use OpenID Connect auth in Insomnia (with Google, at least).
The problem is that OpenID auth returns the token in the `id_token` param, instead of `access_token`. This has been previously discussed in #839.
This PR fixes the issue by doing the following:
- Watch for `id_token=` as well as `access_token=` to detect the redirect.
- If response type is `id_token`, get the token from `id_token` instead of `access_token`.
With this change, Google OpenID Connect auth works, with the following settings:
=> Add support for extracting id_token from oauth2 implicit flow redirect.

packages/insomnia-app/app/common/__tests__/import.test.js, packages/insomnia-app/app/common/import.js, packages/insomnia-app/app/plugins/context/__tests__/data.test.js, packages/insomnia-app/app/plugins/context/data.js, packages/insomnia-app/app/ui/components/export-requests/request-group-row.js, packages/insomnia-app/app/ui/components/export-requests/request-row.js, packages/insomnia-app/app/ui/components/export-requests/tree.js, packages/insomnia-app/app/ui/components/modals/export-requests-modal.js, packages/insomnia-app/app/ui/components/modals/settings-modal.js, packages/insomnia-app/app/ui/components/settings/import-export.js, packages/insomnia-app/app/ui/components/wrapper.js, packages/insomnia-app/app/ui/containers/app.js, packages/insomnia-app/app/ui/css/components/export-requests.less, packages/insomnia-app/app/ui/css/index.less, packages/insomnia-app/app/ui/redux/modules/global.js
Closes: #1273
I implemented the feature to export only certain folders and/or requests in a single workspace.
There is an alternative to this solution which is adding checkboxes in the sidebar, but IMO this makes the exporting not focusable (it's sidebar), and it's more complex in that other components in the sidebar may be disabled, etc.
**UI**
I added a new option "Current Workspace's Requests" under "Export Data" dropdown button.
If the option is chosen, then it will open a new dialog displaying the requests tree of the current workspace.
The initial state is that all folders are expanded and none of the checkboxes is selected. If no folders or requests are selected, then the "Export" button will be disabled.
When the "Export" button is pressed, the flow will be the same as the …
=> Export folders and requests

packages/insomnia-app/app/plugins/context/__tests__/request.test.js, packages/insomnia-app/app/plugins/context/request.js
This PR enables plugin developers to set and get the authentication configuration of a request. 
I built a [small plugin](https://github.com/samirnijenhuis/insomnia-plugin-env-authentication) that allows me to define my OAuth 2 settings on an environment and automate the authentication for every request I add to my workspace. This way I don't have to look / configure auth settings for every single request.
The following issues could benefit from this pr:
https://github.com/getinsomnia/insomnia/issues/1116
https://github.com/getinsomnia/insomnia/issues/790
=> Add request authentication getter and setter to plugin request context.

packages/insomnia-app/app/ui/components/sidebar/sidebar-request-group-row.js, packages/insomnia-app/app/ui/css/components/sidebar.less
Closes #1329.
- Use existing behavior for moving `Request` or `RequestGroup` into an expanded folder.
- Should support moving `Request` to collapsed `RequestGroup`
- Should support moving `RequestGroup` to collapsed `RequestGroup`
- Should support moving any nested combination of `Request` and `RequestGroup`
Initial attempt was to expand the collapsed group on drag-hover. Works, but far from ideal because in the case of multiple `RequestGroup` rows, **all** would open when dragging something from the top of the list to the bottom.
I investigated a hover delay but there is no built-in functionality to `react-dnd` to achieve this. Modifying the package feels too clunky and would be another thing to maintain.
I investigated dropping a `Request` onto the collapsed `RequestGroup` and have it …
=> Move request to collapsed folder by opening on hover

packages/insomnia-app/app/common/import.js, packages/insomnia-app/app/ui/components/modals/error-modal.js, packages/insomnia-importers/src/__tests__/fixtures/swagger2/user-example-input.json, packages/insomnia-importers/src/__tests__/fixtures/swagger2/user-example-output.json, packages/insomnia-importers/src/importers/swagger2.js
Fixes #1354
This PR changes the Swagger importer to try continuing the import even if validation fails. At the validation step, we already know it's a Swagger 2.0 document, so trying to continue is better than just bailing out and giving up.
=> Try importing Swagger even if validation fails

packages/insomnia-app/app/ui/components/settings/general.js, packages/insomnia-app/flow-typed/font-scanner.js, packages/insomnia-app/package-lock.json, packages/insomnia-app/package.json
Fixes #1453
This change replaces the `font-manager` module with `font-scanner`. There seem to be some issues with `font-manager` crashing Node on certain devices. `font-scanner` is an improved fork and seems to handle these issues better. 
The _fix_ here is to simply not show the font selector when no fonts are returned.
=> Replace font-manager with improved font-scanner module 

packages/insomnia-app/app/common/hotkeys.js, packages/insomnia-app/app/models/settings.js, packages/insomnia-app/app/ui/components/settings/shortcuts.js, packages/insomnia-app/app/ui/containers/app.js
Closes #1464
This PR adds a new request "quick create" hotkey which will create a request without showing the dialog box that prompts for request name/method/body
=> Added a request "quick create" hotkey

packages/insomnia-app/app/common/render.js, packages/insomnia-app/app/plugins/context/index.js, packages/insomnia-app/app/plugins/context/network.js, packages/insomnia-app/app/templating/base-extension.js, plugins/insomnia-plugin-response/index.js
Closes #286 (Wow that's an old one)
This PR improves the Response Template Tag to add the ability to resend the request it's dependent on automatically.
- Add a new _behavior_ argument
- never send
- always send
- only if no responses exist
- Add new `network` plugin context with `sendRequest` method
- Actually save the response so it shows in the UI
- Only send the dependent request when rendering for a send (vs visual preview), unless no responses exist yet.
=> Ability to resend Response Tag's dependent request

packages/insomnia-app/app/common/constants.js
The https://developer.mozilla.org/en-US/docs/Web/HTTP/Status page do say that the 405 should not be returned for GET and HEAD. But if you click on that 405 link it will open https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405, and there there's nothing about mandatory methods.
On that page you will get the RFC link https://tools.ietf.org/html/rfc7231#section-6.5.5, and again, there's nothing about mandatory methods.
The restful documentation also doesn't talk about mandatory methods for 405: https://restfulapi.net/http-status-codes/
Spring Framework (a well know framework for Java) has some default configurations for the Spring Data Rest project that will result in GET requests returning 405.
Since the RFC should be the winner here, and the divergence between the mozilla's pages, …
=> Fix 405 HTTP status description

packages/insomnia-app/app/common/render.js, packages/insomnia-app/app/network/network.js, packages/insomnia-app/app/plugins/context/network.js, plugins/insomnia-plugin-response/__tests__/index.test.js, plugins/insomnia-plugin-response/index.js
Fixes #1500 
This PR fixes the Response Tag rendering recursively forever.
- Add `extraInfo` key/value parameter to render
- Add ability to pass `extraInfo` in `network.send()`
- Set `extraInfo` `fromResponseTag = true` within Response Tag
- Check `fromResponseTag` within  Response Tag to see if it triggered recursively
- If recursive, don't trigger a send no matter what
=> Fix Response Tag infinite recursion

packages/insomnia-app/.electronbuilder
Change made due to documentation [here](https://www.electron.build/configuration/squirrel-windows).
The Insomnia app currently has no icon in Control Panel for the app:
This change gives Insomnia the correct icon in Control Panel and Windows Settings:
Unfortunately does **not** solve #1405, this seems to be a bug upstream and since [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) is deprecated, likely will not be fixed, see that issue for discussion.
=> Add iconUrl to electron-builder config so it populates in Control Panel and Windows Settings properly

packages/insomnia-app/app/account/session.js, packages/insomnia-app/app/ui/components/base/link.js, packages/insomnia-app/app/ui/components/modals/settings-modal.js, packages/insomnia-app/app/ui/components/settings/account.js, packages/insomnia-app/app/ui/containers/app.js, packages/insomnia-app/app/ui/css/layout/base.less
Password resets have always been a pain because of the use of E2EE – making it impossible to reset your password without knowing your old one. The solution until now was to delete the users account and create a new one. 
However, since the app keeps a copy of your keys around locally, it's able to perform all necessary actions needed to change a password without knowing the old one. This PR adds a change password form to the account tab in settings to allow the user to change their password.
Since the old password is not needed, a confirmation code (sent by email) is used instead to ensure some level of protection.
=> Add ability to change password

packages/insomnia-app/app/models/request-meta.js, packages/insomnia-app/app/ui/components/request-pane.js, packages/insomnia-app/app/ui/components/request-url-bar.js, packages/insomnia-app/app/ui/components/wrapper.js, packages/insomnia-app/app/ui/containers/app.js
Closes #1511.
Saves request download path in `request-meta` instead of `request-url-bar` state. This allows the setting to be per request rather than global.
Ideally I would expect this `downloadPath` setting (and others in future) to exist in a 'requestSettings` object in meta and passed around as a whole rather than adding x props for each new setting. I feel that is out of scope for this PR though - thoughts?
Send + download
Send only
=> Download path settings per request

packages/insomnia-importers/src/importers/swagger2.js
When playing with Docker Engine API:
https://docs.docker.com/engine/api/v1.39/
I found that it failed to import Swagger spec provided by Docker:
https://docs.docker.com/engine/api/v1.39/swagger.yaml
After some digging it seems when generating parameter example for object types, the swagger importer always assumes the existence of `properties` key, but it's not always the case, for example, from the Docker Engine API spec:
https://gist.github.com/forresty/374c79137e3ce997daead2e73ff92758#file-docker-swagger-insomnia-yaml-L811-L821
This `ExposedPorts` does not have a `properties` key, results in a "failed to import" error.
This tiny patch fixes this problem, now it handles all endpoint definitions of the Docker Engine API yaml file and has nice examples:
Note that some small changes need to …
=> [fix] swagger importer: do not assume object param type has properties

plugins/insomnia-plugin-prompt/index.js
I have added an option to the prompt plugin to save the last entered value and have that set as default value the next time the prompt shows. This saves you from having to enter all details for each request while still being able to change them if needed.
This should be full backwards compatible as the old behaviour is used when a storage key is set explicitly.
1. User executes a request with a few prompt tags
2. User enters details for each of them
3. User sips some coffee, fixes some bugs in his code.
4. User executes the request again
5. User has to enter all details again and make sure they are exactly the same
6. Repeat from step 3
1. User executes a request with a few prompt tags
2. User enters details for each of them
3. User sips some coffee, fixes some bugs in his code.
4. User …
=> [Prompt] Optionally make the prompt plugin pre-fill the last entered value

packages/insomnia-app/app/ui/components/editors/body/body-editor.js
Fix race condition on setting request body and headers to ensure the file is selected after content-type change
Closes #1542
=> Fix file not being selected on content-type change

packages/insomnia-app/app/common/hotkeys.js, packages/insomnia-app/app/main/window-utils.js, packages/insomnia-app/app/ui/components/settings/shortcuts.js, packages/insomnia-app/app/ui/containers/app.js
Closes #1547.
As per title and issue description. Also removes hotkey definition for sidebar toggle (consistent with the other menu items that have associated keyboard shortcuts).
=> Add back View > Toggle Sidebar item

packages/insomnia-app/app/common/import.js, packages/insomnia-cookies/package-lock.json, packages/insomnia-importers/package-lock.json, packages/insomnia-importers/src/__tests__/fixtures.test.js, packages/insomnia-importers/src/__tests__/fixtures/openapi3/dereferenced-output.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/dereferenced-with-tags-output.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-output.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-readonly-output.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-with-tags-output.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-yml-input.yml, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-yml-output.json, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-yml-with-tags-input.yml, packages/insomnia-importers/src/__tests__/fixtures/openapi3/petstore-yml-with-tags-output.json, packages/insomnia-importers/src/importers/openapi3.js, packages/insomnia-libcurl/package-lock.json, packages/insomnia-xpath/package-lock.json, plugins/insomnia-plugin-cookie-jar/package-lock.json, plugins/insomnia-plugin-jsonpath/package-lock.json, plugins/insomnia-plugin-now/package-lock.json, plugins/insomnia-plugin-os/package-lock.json, plugins/insomnia-plugin-uuid/package-lock.json
This PR makes the OpenAPI importer generate deterministic IDs. This is necessary if you want to be able to import the same spec a second time and have it update already existing requests/folders/environments instead of creating new ones.
=> Make OpenAPI importer generate deterministic IDs

packages/insomnia-app/app/common/render.js, packages/insomnia-app/app/ui/components/codemirror/extensions/nunjucks-tags.js
(Fixes #1288) Extract parent from nunjucks tag when it is a nested property nested. The parent is then used to fetch the keyContext
=> [Bug Fix 1288] "Undefined" for nested variables

packages/insomnia-app/app/network/o-auth-2/__tests__/grant-password.test.js, packages/insomnia-app/app/network/o-auth-2/get-token.js, packages/insomnia-app/app/network/o-auth-2/grant-password.js, packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
=> Audience parameter for Resource Owner Password Credentials

packages/insomnia-app/app/ui/css/editor/general.less
=> Fix transparent line-numbers background

packages/insomnia-app/app/plugins/install.js
Additional fix to PR #1688
I have downloaded 7.0.0 update today and unfortunately It didn't fully fix the issue on windows. The `_getYarnPath()` also should be escaped, but I have missed that since yarn-standalone was installed in the path without space on my local env :(
I have added spaces locally to plugin and yarn folders and now it works
=> Escape yarn paths

packages/insomnia-app/app/ui/redux/modules/global.js
Noticed a typo that showed up when importing certain file types, thought I'd open a quick PR to fix it:
=> Correct typo on import dialog

packages/insomnia-app/app/ui/components/codemirror/code-editor.js
Fixes https://github.com/getinsomnia/insomnia/issues/1694
Problem here was that `extraKeys` got overridden on initialization. Made sure to include the base options in the override. Comment toggling and other custom hotkeys should now work again in the editor.
=> No longer override `extraKeys` in CodeMirror on initialization

packages/insomnia-app/app/network/o-auth-2/refresh-token.js
I know the PR says to open an issue first, but I figured this could be the discussion as I've already done part of the work.
At my current workplace we have an oauth server with access tokens on a 5 min TTL and refresh tokens on a 30 min TTL. So every so often I'll see the following message.
It's rather annoying to have to go into the OAuth page to clear the tokens and refresh it again. Given Insomnia automatically handles fetching the access / refresh. I'm sure it should be able to ignore this and fetch new tokens if it encounters this error.
So, as per the oauth spec [here](https://tools.ietf.org/html/rfc6749#section-5.2), I've updated the refreshToken function to return the magic response that will trigger a new token to be fetched if the server sends back `400` status, and the `error` …
=> Fetch new access tokens if refreshing token returns "invalid_grant"

packages/insomnia-app/app/common/misc.js, packages/insomnia-app/app/ui/components/sidebar/sidebar-request-row.js, packages/insomnia-app/app/ui/components/tags/method-tag.js, packages/insomnia-app/app/ui/css/components/tag.less
This PR adds first class display support for the `X-HTTP-Method-Override` header in the sidebar.
Whenever the `X-HTTP-Method-Override` header is set with a valid method name on a request, the request in sidebar shows the overriding method, with the overridden method shown smaller. 
Closes #1334.
=> [Feature] Added display support for X-HTTP-Method-Override

packages/insomnia-app/app/ui/components/tags/method-tag.js
Fixes failing build due to ESLint `no-unneeded-ternary` error
(it was my commit that introduced the error - sorry! :sweat_smile:   ).
=> Fix build failing

packages/insomnia-app/app/ui/components/dropdowns/response-history-dropdown.js, packages/insomnia-app/flow-typed/moment.js
Modifies the response history dropdown to group the responses into time groups, as shown:
Closes #831
=> [Feature] Added response history grouping by time

packages/insomnia-app/app/ui/components/editors/request-headers-editor.js
Now that I'm at it here's a tiny consistency PR. 'name' and 'value' is written lower case in both the form and the query editor, so 'header' and 'value' in the header editor should also be lower case - or all of them upper case ;-)
=> Make 'value' and 'header' lower case for consistency

packages/insomnia-app/app/ui/components/templating/variable-editor.js
Closes [#1791](https://github.com/getinsomnia/insomnia/issues/1791)
=> Dynamic height of window "Edit variable" - "Line preview"

packages/insomnia-app/app/network/o-auth-2/__tests__/grant-authorization-code.test.js, packages/insomnia-app/app/network/o-auth-2/get-token.js, packages/insomnia-app/app/network/o-auth-2/grant-authorization-code.js, packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.js
This adds the optional field `audience` and `resource` used in OAuth 2 client credentials authorization flow against [SciTokens](https://scitokens.org/) servers.
Closes #1767
=> Add audience and resource field for OAuth2 Authorization Code grant

packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js
The problem appears to be the fact that the GraphQL editor is only updated at initialization time, and when the text in it changes.
The [`render()` function](https://github.com/getinsomnia/insomnia/blob/d2670912666228f5a8b0b78fad0b7804d9b8f85e/packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js#L527) gathers some state that is used to construct a [`variableTypes` object](https://github.com/getinsomnia/insomnia/blob/d2670912666228f5a8b0b78fad0b7804d9b8f85e/packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js#L553), which is then used in the component HTML to specify the [linter options](https://github.com/getinsomnia/insomnia/blob/d2670912666228f5a8b0b78fad0b7804d9b8f85e/packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js#L670). …
=> Add GraphQL lint to editor component mount (Fixes #1507)

packages/insomnia-app/app/common/constants.js
The 201 HTTP status is most typically the result of a POST request.
Apparently, this came verbatim from MDN where it was fixed in
https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Status$compare?to=1348890&from=1340759
=> Fix the description of HTTP 201 Created

packages/insomnia/src/ui/components/command-palette.tsx
=> fix: propagate `organizationId` when opening the search dialog
